name: QMagFace
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=21
  - scikit-image
  - scikit-learn
  - tqdm
  - click
  - opencv
  - pytorch
  - cudatoolkit
  - torchvision
  - numpy
  - prettytable
  - pandas
  - pip:
      - mxnet