name: QMagFace
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip=21
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - scikit-learn
  - scikit-image
  - tqdm
  - termcolor
  - click
  - pip:
      - opencv-contrib-python
      - mxnet